### ISSUE TITLE
java.lang.Exception: Mod Loading has failed Forge 1.171.

### ISSUE THREAD

**Issue by lays24mc** [Kotori316/QuarryPlus#141]
## Describe the bug

Server crash with "Mod Loading has failed"

```
Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
		at com.yogpc.qp.packet.PacketHandler.init(PacketHandler.java:52) ~[AdditionalEnchantedMiner-1.17-17.5-SNAPSHOT.jar%2327!:17.5-SNAPSHOT] {re:classloading}
		at com.yogpc.qp.QuarryPlus$Register.setup(QuarryPlus.java:75) ~[AdditionalEnchantedMiner-1.17-17.5-SNAPSHOT.jar%2327!:17.5-SNAPSHOT] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_237_Register_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at com.kotori316.scala_lib.ScalaModContainer.acceptEvent(ScalaModContainer.java:125) ~[ScalableCatsForce-2.13.6-build-4-with-library.jar%2392!:2.13.6-build-4] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.97.jar%23116!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

## To Reproduce

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.17.1]
* Single Player or Multi Player?: [Multiplayer]
* Forge version: [37.0.97]
* QuarryPlus version: [1.17-17.5-SNAPSHOT]

## Crash report or logs

https://pastebin.com/pXnWhywX

**Comment by Kotori316** [comment]
Thank you for your reporting. I fixed and released v17.6
