### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by mgs3** [Kotori316/QuarryPlus#220]
## Describe the bug

Just fresh install minecraft forge, download mods AdditionalEnchantedMiner and run.

## To Reproduce

1. fresh install forge
2. eula = true
3. download 2 mods
4. run.sh

If your server/client has crashed, please give me the crash report.

## Versions

* Debian [11.5]
* Minecraft version: [1.9.2]
* Multi Player
* Forge version: [43.1.52]
```
$/data/minecraftforge/mods$ ls
AdditionalEnchantedMiner-1.19.2-19.9.jar  ScalableCatsForce-2.13.10-build-12-with-library.jar
$/data/minecraftforge/mods$
```

## Crash report or logs

```
 ./run.sh
[18:01:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.1.52, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[18:01:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4 by Debian; OS Linux arch amd64 version 5.10.0-19-amd64
[18:01:56] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/data/minecraftforge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[18:01:56] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/minecraftforge/libraries/net/minecraftforge/fmlcore/1.19.2-43.1.52/fmlcore-1.19.2-43.1.52.jar is missing mods.toml file
[18:01:56] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/minecraftforge/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.1.52/javafmllanguage-1.19.2-43.1.52.jar is missing mods.toml file
[18:01:56] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/minecraftforge/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.1.52/lowcodelanguage-1.19.2-43.1.52.jar is missing mods.toml file
[18:01:56] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /data/minecraftforge/libraries/net/minecraftforge/mclanguage/1.19.2-43.1.52/mclanguage-1.19.2-43.1.52.jar is missing mods.toml file
[18:01:57] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[18:01:58] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[18:02:01] [main/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
[18:02:02] [main/FATAL] [co.ko.sc.ScalaLanguageProvider$/LOADING]: Failed to build mod
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
```

[crash-2022-11-19_18.02.02-fml.txt](https://github.com/Kotori316/QuarryPlus/files/10047586/crash-2022-11-19_18.02.02-fml.txt)

**Comment by mgs3** [comment]
On client, (Windows 10)

Just start minecraft with forge :

<img width="1920" alt="onwin10" src="https://user-images.githubusercontent.com/18463612/202863731-9e91ee0a-77a9-4f45-8b17-4c78429f3908.png">


[crash-2022-11-19_18.24.52-fml.txt](https://github.com/Kotori316/QuarryPlus/files/10047603/crash-2022-11-19_18.24.52-fml.txt)

**Comment by mgs3** [comment]
Ok, ScalableCatsForce for 1.18 Uu
