### ISSUE TITLE
Duplicated Filler

### ISSUE THREAD

**Issue by georgio3333** [Kotori316/QuarryPlus#249]
## Describe the bug

The Filler is infinitely duplicable when you hold it in your hands (sneak+click) and want to put it down. Even after being dead.

## To Reproduce

1. just take it with your hand and try to put it down
2. 
3. 

If your server/client has crashed, please give me the crash report.
no crash
## Versions

* Minecraft version: [1.19.2]
* Single Player or Multi Player?: [Multi]
* Fabric Loader version: [0.14.12]
* Fabric Api version: [0.69.0]
* QuarryPlus version: [19.1.672]
* Other mods: 
[
AdditionalEnchantedMiner-1.19-fabric-19.1.672.jar
AttributeFix-Fabric-1.19.2-17.1.2.jar
Bookshelf-Fabric-1.19.2-16.2.16.jar
BowInfinityFix-1.19.x-fabric-2.5.0.jar
CITResewn-1.1.2+1.19.2.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
Companion-1.19.2-fabric-3.1.2.jar
CorgiLib-fabric-1.19.2-1.0.0.6.jar
Couplings-1.9.1+1.19.jar
Croptopia-1.19.2-FABRIC-2.1.2.jar
DimThread-1.2.7.jar.disabled
EasyAnvils-v4.0.6-1.19.2-Fabric.jar
EasyMagic-v4.3.2-1.19.2-Fabric.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.13.jar
Enhanced_Celestials-fabric-1.19.2-2.1.0.2.jar
Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
ExplorersCompass-1.19.2-2.2.0-fabric.jar
FallingTree-1.19.2-3.10.0.jar
ForgeConfigAPIPort-v4.2.9-1.19.2-Fabric.jar
FriendlyFire-Fabric-1.19.2-14.0.1.jar
InventorySorter-1.8.10-1.19.jar
IronChests-1.7.7.jar
Jade-1.19.1-fabric-8.6.3.jar
MagnumTorch-v4.2.0-1.19.2-Fabric.jar
Mo-Glass-1.6.1-MC1.19.2.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
OpenLoader-Fabric-1.19.2-15.0.1.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.6.1+1.14.4-1.19.3.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
RebornCore-5.4.0.jar
Regrowth-1.19-41.1.31.1.jar
RoughlyEnoughItems-9.1.580.jar
TechReborn-5.4.0.jar
Terralith_v2.3.6.jar
The_Graveyard_2.3_(FABRIC)_for_1.19.2.jar
Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
VisualWorkbench-v4.2.0-1.19.2-Fabric.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
adventurez-1.4.17.jar.disabled
animal_feeding_trough-1.0.3+1.19.2.jar
appleskin-fabric-mc1.19-2.4.1.jar
arcanus-1.30.jar
architectury-6.4.62-fabric.jar
axolotl-item-fix-1.1.4.jar
badpackets-fabric-0.2.1.jar
balm-fabric-4.5.2+0.jar
bclib-2.1.5.jar
better-end-2.1.2.jar
better-nether-7.1.2.jar
betteranimalsplus-1.19.2-11.0.9-fabric.jar
blockus-2.5.6+1.19.2.jar
carrier-1.11.0.jar
chalk-2.1.0+1.19.jar
chalk-colorful-addon-2.1.1.jar
charmofundying-fabric-6.0.0+1.19.2.jar
chisel-1.4.7+1.19.2.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.22.jar
comforts-fabric-6.0.3+1.19.2.jar
compact_storage_fabric-5.0_lts_b2_1.19.2.jar
continuity-2.0.1+1.19.jar
craftingtweaks-fabric-1.19-15.1.0.jar
crawl-0.11.1.jar
dawn-3.5.0.jar
dragonloot-1.1.2.jar
ecologics-fabric-1.19.2-2.1.11.jar
energy-2.3.0.jar
enhancedblockentities-0.7.2+1.19.2.jar
entity-view-distance-1.0.2+1.19.jar
entityculling-fabric-1.5.2-mc1.19.jar
extra-generators-1.2.1-BETA+1.19.jar
fabric-api-0.69.0+1.19.2.jar
fabric-language-kotlin-1.8.7+kotlin.1.7.22.jar
fabric-language-scala-1.1.0+scala.2.13.6-fat.jar
fabric-quarry-1.19.2-1.0.3.jar
fallingleaves-1.13.0+1.19.2.jar
ferritecore-5.0.3-fabric.jar
frame-0.26.1+1.19-fabric.jar
ftb-chunks-fabric-1902.3.14-build.218.jar
ftb-library-fabric-1902.3.11-build.166.jar
ftb-quests-fabric-1902.4.4-build.150.jar
ftb-teams-fabric-1902.2.11-build.87.jar
geckolib-fabric-1.19-3.1.38.jar
giacomos_bookshelf1.3.4-1.19.2.jar
gravestone-1.19.2-1.0.1.jar
immersive-portals-2.3.1-mc1.19.2-fabric.jar.disabled
indium-1.0.9+mc1.19.2.jar
indrev-1.15.1-BETA.jar
invhud.fabric.1.19-3.4.7.jar
iris-mc1.19.2-1.4.5.jar.disabled
item-filters-fabric-1902.2.9-build.46.jar
jmi-fabric-1.19.2-0.13-30.jar
journeymap-1.19.2-5.9.0-fabric.jar
kibe-1.9.10-BETA+1.19.jar
lithium-fabric-mc1.19.2-0.10.4.jar
mcda-2.2.0.jar
mcdar-1.5.2-1.19.jar
mcdw-5.0.4-1.19.jar
mcw-bridges-2.0.5-mc1.19fabric.jar
mcw-doors-1.0.7fabric-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2fabric.jar
mcw-lights-1.0.4fabric-mc1.19.2.jar
mcw-roofs-2.2.2-mc1.19.2fabric.jar
mcw-trapdoors-1.0.8-mc1.19.2fabric.jar
mcw-windows-2.1.1-mc1.19.2fabric.jar
megane-8.3.0.jar
memoryleakfix-1.19.1-0.7.0.jar
midnightlib-fabric-1.0.0.jar
modmenu-4.1.2.jar
moonlight-1.19.2-2.1.20-fabric.jar
moreculling-1.19.1-0.13.0.jar
mythic-mounts-1.19.2-7.1.jar
nicemod-1.2+-+1.19.2.jar
notenoughcrashes-4.2.1+1.19.2-fabric.jar
observable-1.19.2-3.3.1.jar.disabled
oxidized-1.7.2.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
plushie-mod-1.2.jar
polymorph-fabric-0.46.1+1.19.2.jar
quartz-elevator-2.1.5+1.19.jar
repurposed_structures_fabric-6.1.3+1.19.2.jar
rer-2.6.0.jar
respawnablepets-1.19-2.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.18.jar
spark-1.9.45-fabric.jar
supplementaries-1.19.2-2.2.29-fabric.jar
toms_storage_fabric-1.19-1.4.5.jar
tooltipfix-1.1.1-1.19.jar
torohealth-1.19-fabric-1.jar
trashslot-fabric-1.19-12.0.1.jar
trinkets-3.4.1.jar
twigs-2.0.0-beta.9+1.19-fabric.jar
universal_ores-1.4.2.jar
voidtotem-fabric-1.19.2-2.1.0.jar
waystones-fabric-1.19-11.1.0.jar
wirelessnetworks-1.6.0.jar
wolves-with-armor-1.8.0-1.19.jar
wraith-waystones-3.0.5+mc1.19.2.jar
wthit-fabric-5.13.4.jar
xp_storage-1.4.3+1.19.jar
]

## Crash report or logs
[20:30:35] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@3932ec50, suppressing error
java.lang.IllegalArgumentException: Invalid tag for SkipIterator. {iterator:{area:{direction:"north",maxX:-1558,maxY:68,maxZ:613,minX:-1568,minY:68,minZ:603},current:-428259776548796L,skips:[L;],type:"BOX"}}
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at com.yogpc.qp.machines.filler.SkipIterator.lambda$fromNbt$0(SkipIterator.java:71) ~[AdditionalEnchantedMiner-1.19-fabric-19.1.672.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.yogpc.qp.machines.filler.SkipIterator.fromNbt(SkipIterator.java:70) ~[AdditionalEnchantedMiner-1.19-fabric-19.1.672.jar:?]
	at com.yogpc.qp.machines.filler.FillerAction.fromNbt(FillerAction.java:80) ~[AdditionalEnchantedMiner-1.19-fabric-19.1.672.jar:?]
	at com.yogpc.qp.machines.filler.FillerEntity.readNbt(FillerEntity.java:56) ~[AdditionalEnchantedMiner-1.19-fabric-19.1.672.jar:?]
	at me.steven.carrier.impl.CarriableGeneric.tryPlace(CarriableGeneric.java:67) ~[carrier-1.11.0.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:43) ~[carrier-1.11.0.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:74) ~[carrier-1.11.0.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.handler$zli000$carrier_interactBlock(AbstractBlock:1155) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:964) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:338) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1145) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:34) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:159) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:736) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:669) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.
[latest.log](https://github.com/Kotori316/QuarryPlus/files/10875548/latest.log)

**Comment by Kotori316** [comment]
I'm sorry I can't reproduce the duplication. The Filler item doesn't have NBT tag in my environment, so a placement should succeed without error.

As for error in your log, `java.lang.IllegalArgumentException: Invalid tag for SkipIterator`, I fixed. I hope this will fix the duplication.

Install latest version for 1.19.2 and try the machine.
