### ISSUE TITLE
Flexible marker GUI click causes crash.

### ISSUE THREAD

**Issue by decryptedchaos** [Kotori316/QuarryPlus#271]
## Describe the bug
Due to the  bug(?) of the missing recipe for the Marker plus  I tried using the flexible marker and it's got a pretty severe bug
When using the Flexible marker,  and clicking the down double arrow in the GUI the game crashes consistently every time

_What happened to you?_

## To Reproduce

1. Place Flexible marker 
2. Open GUI
3. Click down double arrow once or twice..  

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [Single]
* Forge version: [47.1.3]
* QuarryPlus version: [AdditionalEnchantedMiner-1.20.1-1201.0.14-SNAPSHOT]
* Other mods: [Many ?  ATM9 give or take]

## Crash report or logs
```
[25Aug2023 15:50:07.357] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 173.9 ?s
[25Aug2023 15:50:07.358] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 187.5 ?s
[25Aug2023 15:50:07.360] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 124.7 ?s
[25Aug2023 15:50:07.360] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 230.7 ?s
[25Aug2023 15:50:07.361] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 250.7 ?s
[25Aug2023 15:50:07.361] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 144.5 ?s
[25Aug2023 15:50:07.362] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 54.00 ?s
[25Aug2023 15:50:07.362] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 46.90 ?s
[25Aug2023 15:50:07.363] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 31.80 ?s
[25Aug2023 15:50:07.363] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 238.3 ?s
[25Aug2023 15:50:07.364] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 534.7 ?s
[25Aug2023 15:50:07.366] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 403.6 ?s
[25Aug2023 15:50:07.367] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 51.20 ?s
[25Aug2023 15:50:07.367] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 30.00 ?s
[25Aug2023 15:50:07.367] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 19.90 ?s
[25Aug2023 15:50:07.369] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 1.042 ms
[25Aug2023 15:50:07.370] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 1.133 ms
[25Aug2023 15:50:07.373] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 1.077 ms
[25Aug2023 15:50:07.375] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 501.7 ?s
[25Aug2023 15:50:07.375] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 583.8 ?s
[25Aug2023 15:50:07.382] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 639.5 ?s
[25Aug2023 15:50:07.452] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 237.5 ?s
[25Aug2023 15:50:07.452] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 256.0 ?s
[25Aug2023 15:50:07.454] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader: Files found in 150.4 ?s
[25Aug2023 15:50:07.462] [Render thread/INFO] [ModernFix/]: Cleared 186 unneeded book NBT tags
[25Aug2023 15:50:08.478] [Render thread/WARN] [ModernFix/]: Time from main menu to in-game was 86.194534 seconds
[25Aug2023 15:50:08.479] [Render thread/WARN] [ModernFix/]: Total time to load game and open world was 194.48453 seconds
[25Aug2023 15:50:10.272] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 2081ms or 41 ticks behind
[25Aug2023 16:00:01.168] [repurposedstructures-1-thread-1/WARN] [ModernFix/]: The namespace repurposed_structures contains an outdated structure file, which can cause worldgen lag. Please view debug.log for the full filename, determine which mod provides the structure, and report to the mod/datapack author, including the debug log.
[25Aug2023 16:01:08.256] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[25Aug2023 16:01:08.257] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[25Aug2023 16:01:08.302] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: ArchNemesiss lost connection: Disconnected
[25Aug2023 16:01:08.302] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ArchNemesiss left the game
[25Aug2023 16:01:08.361] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[25Aug2023 16:01:08.361] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[25Aug2023 16:01:08.551] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/minecraft:overworld
[25Aug2023 16:01:08.702] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:mars
[25Aug2023 16:01:08.709] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/minecraft:the_end
[25Aug2023 16:01:08.715] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:moon_orbit
[25Aug2023 16:01:08.721] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/blue_skies:everbright
[25Aug2023 16:01:08.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:mercury
[25Aug2023 16:01:08.737] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/twilightforest:twilight_forest
[25Aug2023 16:01:08.745] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/minecraft:the_nether
[25Aug2023 16:01:08.749] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/undergarden:undergarden
[25Aug2023 16:01:08.756] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:glacio
[25Aug2023 16:01:08.763] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:venus_orbit
[25Aug2023 16:01:08.771] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/lostcities:lostcity
[25Aug2023 16:01:08.779] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:mercury_orbit
[25Aug2023 16:01:08.785] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/blue_skies:everdawn
[25Aug2023 16:01:08.794] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:glacio_orbit
[25Aug2023 16:01:08.802] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:earth_orbit
[25Aug2023 16:01:08.809] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:mars_orbit
[25Aug2023 16:01:08.816] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:venus
[25Aug2023 16:01:08.824] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ad_astra:moon
[25Aug2023 16:01:08.832] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/mahoutsukai:reality_marble
[25Aug2023 16:01:08.841] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[Hexan]'/ae2:spatial_storage
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (Hexan): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (moon_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (everbright): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mercury): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (undergarden): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (glacio): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (venus_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (lostcity): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mercury_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (everdawn): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (glacio_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (earth_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mars_orbit): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (venus): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (moon): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (reality_marble): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[25Aug2023 16:01:09.129] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[25Aug2023 16:01:09.661] [Server thread/INFO] [shetiphian.endertanks.EnderTanks/]: Unloading EnderTank Data
[25Aug2023 16:01:09.661] [Server thread/INFO] [shetiphian.endertanks.EnderTanks/]: Finished Unloading EnderTank Data
[25Aug2023 16:01:09.661] [Server thread/INFO] [shetiphian.enderchests.EnderChests/]: Unloading EnderChest Data
[25Aug2023 16:01:09.661] [Server thread/INFO] [shetiphian.enderchests.EnderChests/]: Finished Unloading EnderChest Data
[25Aug2023 16:01:09.729] [Server thread/INFO] [FluxNetworks/Energy]: Energy blacklist loaded: 1 block entries, 0 item entries
[25Aug2023 16:01:09.738] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[25Aug2023 16:01:09.738] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[25Aug2023 16:01:09.738] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[25Aug2023 16:01:09.739] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable...
[25Aug2023 16:01:09.739] [Render thread/INFO] [mezz.jei.forge.plugins.forge.ForgeGuiPlugin/]: Stopping JEI GUI
[25Aug2023 16:01:09.743] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable took 4.232 ms
[25Aug2023 16:01:09.743] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
[25Aug2023 16:01:09.760] [Render thread/INFO] [minecolonies/]: Removed all colony views
[25Aug2023 16:01:09.766] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[25Aug2023 16:01:11.198] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at com.yogpc.qp.machines.marker.TileFlexMarker$Movable.valueOf(TileFlexMarker.java:177) ~[AdditionalEnchantedMiner-1.20.1-1201.0.14-SNAPSHOT.jar%23475!/:1201.0.14-SNAPSHOT]
	at com.yogpc.qp.machines.marker.ScreenFlexMarker.actionPerformed(ScreenFlexMarker.java:124) ~[AdditionalEnchantedMiner-1.20.1-1201.0.14-SNAPSHOT.jar%23475!/:1201.0.14-SNAPSHOT]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:175) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:276) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23782!/:?]
	... 28 more
[25Aug2023 16:01:11.217] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID d8a0a3e2-5fc1-49e4-9b4b-9d3e14084f1c
[25Aug2023 16:01:11.226] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID fcf2dae2-4f57-4767-9dca-2b1d029dac78
```
If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
I released new version for 1.20.1. Try the one.
