### ISSUE TITLE
Ticking Block Entity Crash

### ISSUE THREAD

**Issue by zvvx** [Kotori316/QuarryPlus#279]
## Describe the bug
Game crash while using quarry plus with EU power (IC2 Classic)

Cannot reproduce myself but I was using the quarry plus without markers powered by IC2 classic solar panels with hoppers and a chest below. Notably the quarry hit a cave and I was exploring the cave when the crash occured. Game would crash again on re-entering the world.

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.19.2
* Single Player or Multi Player?: Single player
* Forge version: 43.3.2
* QuarryPlus version: 1192.3.22
* Other mods: Mod listed in crash report

## Crash report or logs

<details><summary>Details</summary>

```

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-11-04 16:42:44
Description: Ticking block entity

java.lang.NullPointerException: Cannot read field "f_19853_" because "entity" is null
	at defeatedcrow.hac.core.material.block.OreBlockGemDC.getAdditionalDrop(OreBlockGemDC.java:67) ~[HeatAndClimate-1.19.2-v4-alpha9.jar%23198!/:1.19.2_v4-alpha9] {re:classloading}
	at defeatedcrow.hac.core.material.block.BlockDC.m_7381_(BlockDC.java:48) ~[HeatAndClimate-1.19.2-v4-alpha9.jar%23198!/:1.19.2_v4-alpha9] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,xf:fml:forgeendertech:coremod,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49874_(Block.java:262) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dcs_climate.json:BlockClassMixin,pl:mixin:A}
	at com.yogpc.qp.machines.InvUtils.getBlockDrops(InvUtils.java:50) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellTile.breakBlock(MiningWellTile.java:146) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellTile.tick(MiningWellTile.java:92) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellBlock.lambda$getTicker$0(MiningWellBlock.java:129) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.utils.CombinedBlockEntityTicker.m_155252_(CombinedBlockEntityTicker.java:30) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ic2.mixins.json:server.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at defeatedcrow.hac.core.material.block.OreBlockGemDC.getAdditionalDrop(OreBlockGemDC.java:67) ~[HeatAndClimate-1.19.2-v4-alpha9.jar%23198!/:1.19.2_v4-alpha9] {re:classloading}
	at defeatedcrow.hac.core.material.block.BlockDC.m_7381_(BlockDC.java:48) ~[HeatAndClimate-1.19.2-v4-alpha9.jar%23198!/:1.19.2_v4-alpha9] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,xf:fml:forgeendertech:coremod,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49874_(Block.java:262) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dcs_climate.json:BlockClassMixin,pl:mixin:A}
	at com.yogpc.qp.machines.InvUtils.getBlockDrops(InvUtils.java:50) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellTile.breakBlock(MiningWellTile.java:146) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellTile.tick(MiningWellTile.java:92) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.machines.miningwell.MiningWellBlock.lambda$getTicker$0(MiningWellBlock.java:129) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at com.yogpc.qp.utils.CombinedBlockEntityTicker.m_155252_(CombinedBlockEntityTicker.java:30) ~[AdditionalEnchantedMiner-1.19.2-1192.3.22.jar%23185!/:1192.3.22] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ic2.mixins.json:server.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: quarryplus:mining_well // com.yogpc.qp.machines.miningwell.MiningWellTile
	Block: Block{quarryplus:mining_well}[facing=north,working=true]
	Block location: World: (-3,64,-12), Section: (at 13,0,4 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{quarryplus:mining_well}[facing=north,working=true]
	Block location: World: (-3,64,-12), Section: (at 13,0,4 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ic2.mixins.json:server.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['zvvx'/213, l='ServerLevel[New World]', x=21.62, y=2.00, z=15.84]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25754 game time, 8498 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 153702 (now: false), thunder time: 95697 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 894902208 bytes (853 MiB) / 4093640704 bytes (3904 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75189.56
	Virtual memory used (MB): 17533.98
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['zvvx'/213, l='ServerLevel[New World]', x=21.62, y=2.00, z=15.84]]
	Data Packs: vanilla, mod:farmersdelight, mod:inventorysorter (incompatible), mod:moonlight (incompatible), mod:quarryplus, mod:jade (incompatible), mod:jei (incompatible), mod:spectrelib (incompatible), mod:volcanic_caverns (incompatible), mod:projecte, mod:obscure_api, mod:hourglass (incompatible), mod:flywheel (incompatible), mod:ic2 (incompatible), mod:create, mod:xaerominimap, mod:forgeendertech, mod:xaeroworldmap, mod:polymorph, mod:configured (incompatible), mod:mixinextras (incompatible), mod:dcs_climate, mod:littlecontraptions (incompatible), mod:createdieselgenerators (incompatible), mod:littlelogistics (incompatible), mod:red_power, mod:adpother, mod:adchimneys, mod:jeresources (incompatible), mod:crafttweaker (incompatible), mod:fallingtree, mod:customwindowtitle (incompatible), mod:forge, mod:advanced_solars (incompatible), mod:playerabilitylib (incompatible), mod:gravisuit (incompatible), mod:supplementaries (incompatible), mod:createaddition (incompatible), Supplementaries Generated Pack, mod:ic2c (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.2-forge-43.3.2
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.2.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.2.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.2.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.2.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.2.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		inventorysorter-1.19.2-21.0.4.jar                 |Simple Inventory Sorter       |inventorysorter               |21.0.4              |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.3-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.3.3        |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.19.2-1192.3.22.jar     |QuarryPlus                    |quarryplus                    |1192.3.22           |DONE      |Manifest: ef:50:af:b3:03:e0:3e:70:a7:ef:78:77:a5:4d:d4:b5:07:ec:df:9d:d6:f3:12:13:c9:3c:cd:9a:0a:3e:6b:43
		Jade-1.19.1-forge-8.9.1.jar                       |Jade                          |jade                          |8.9.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.6+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.6+1.19.2       |DONE      |Manifest: NOSIGNATURE
		volcanic_caverns-1.19.2-1.2.2.jar                 |Volcanic Caverns              |volcanic_caverns              |1.19.2-1.2.2        |DONE      |Manifest: NOSIGNATURE
		ProjectE-1.19.2-PE1.0.1B.jar                      |ProjectE                      |projecte                      |1.0.1B              |DONE      |Manifest: NOSIGNATURE
		obscure_api-15.jar                                |Obscure API                   |obscure_api                   |15                  |DONE      |Manifest: NOSIGNATURE
		hourglass-1.19.1-1.2.1.1.jar                      |Hourglass                     |hourglass                     |1.19.1-1.2.1.1      |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.10-20.jar               |Flywheel                      |flywheel                      |0.6.10-20           |DONE      |Manifest: NOSIGNATURE
		IC2Classic-1.19.2-2.0.7.1.jar                     |IC2 Classic                   |ic2                           |1.19.2-2.0.7.1      |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.4_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.8.4              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.19.2-10.0.6.1-build.0897.jar     |ForgeEndertech                |forgeendertech                |10.0.6.1            |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.36.0_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.36.0              |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.5+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.5+1.19.2       |DONE      |Manifest: NOSIGNATURE
		configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.5.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.5          |DONE      |Manifest: NOSIGNATURE
		HeatAndClimate-1.19.2-v4-alpha9.jar               |HeatAndClimate                |dcs_climate                   |4.0.0               |DONE      |Manifest: NOSIGNATURE
		littlecontraptions-forge-1.19.2.2.jar             |Little Contraptions           |littlecontraptions            |1.19.2.2            |DONE      |Manifest: NOSIGNATURE
		createdieselgenerators-1.19.2-1.2c.jar            |Create Diesel Generators      |createdieselgenerators        |1.19.2-1.2c         |DONE      |Manifest: NOSIGNATURE
		littlelogistics-mc1.19.2-v1.4.0.jar               |Little Logistics              |littlelogistics               |1.4.0               |DONE      |Manifest: NOSIGNATURE
		red_power-1.1.jar                                 |Red Power                     |red_power                     |1.1                 |DONE      |Manifest: NOSIGNATURE
		AdPother-1.19.2-7.0.17.0-build.1034.jar           |Pollution of the Realms       |adpother                      |7.0.17.0            |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.19.2-9.1.14.0-build.1033.jar         |Advanced Chimneys             |adchimneys                    |9.1.14.0            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.1.0.179.jar          |Just Enough Resources         |jeresources                   |1.1.0.179           |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.1.50.jar             |CraftTweaker                  |crafttweaker                  |10.1.50             |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.1.jar                     |FallingTree                   |fallingtree                   |3.10.1              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		CustomWindowTitle-Forge-1.19+v1.1.1.jar           |Custom Window Title           |customwindowtitle             |1.1.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.2-universal.jar                 |Forge                         |forge                         |43.3.2              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		advancedsolars-2.0.3.jar                          |Advanced Solars Classic       |advanced_solars               |2.0.3               |DONE      |Manifest: NOSIGNATURE
		PlayerAbilityLib-forge-b2d633b0ae.jar             |Pal                           |playerabilitylib              |1.6.0               |DONE      |Manifest: NOSIGNATURE
		gravisuit-2.2.jar                                 |Gravisuit Classic             |gravisuit                     |2.2                 |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.4.jar                  |Supplementaries               |supplementaries               |1.19.2-2.4.4        |DONE      |Manifest: NOSIGNATURE
		createaddition-1.19.2-1.1.1.jar                   |Create Crafts & Additions     |createaddition                |1.19.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 5d28d2e3-a658-4c1e-9367-ab7a52abdf5d
	FML: 43.3
	Forge: net.minecraftforge:43.3.2
```
</details>

**Comment by Kotori316** [comment]
It seems this issue is related to https://github.com/defeatedcrow/HeatAndClimateMod/issues/284

**Comment by Kotori316** [comment]
Fixed in the latest version.
Actually, this is not the bug in my mod, but I added some workarounds for this issue.

Thank you for reporting with crash report.
