### ISSUE TITLE
Client crash when using List Editor on a Quarry Plus 1.16.1

### ISSUE THREAD

**Issue by InflamedSebi** [Kotori316/QuarryPlus#94]
When Right clicking a quarry plus with a List editor the client crashes.
<details>
<summary>Crashlog</summary>

```

[19:51:20] [Render thread/FATAL]: Unreported exception thrown!
scala.MatchError: Some(com.yogpc.qp.machines.base.EnchantmentFilter$Accessor$NewQuarryAccessor@24b724f2) (of class scala.Some)
	at com.yogpc.qp.machines.item.ItemListEditor.onItemUseFirst(ItemListEditor.scala:64) ~[?:16.0.4]
	at net.minecraft.item.ItemStack.lambda$onItemUseFirst$6(ItemStack.java:189) ~[?:?]
	at net.minecraft.item.ItemStack$$Lambda$11662/173623542.apply(Unknown Source) ~[?:?]
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200) ~[?:?]
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:189) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:280) ~[?:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1339) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1433) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:927) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.66.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1487365582.call(Unknown Source) [forge-1.16.1-32.0.66.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[19:51:32] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:120]: ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/18/20 7:51 PM
Description: Unexpected error

scala.MatchError: Some(com.yogpc.qp.machines.base.EnchantmentFilter$Accessor$NewQuarryAccessor@24b724f2) (of class scala.Some)
	at com.yogpc.qp.machines.item.ItemListEditor.onItemUseFirst(ItemListEditor.scala:64) ~[?:16.0.4] {re:classloading}
	at net.minecraft.item.ItemStack.lambda$onItemUseFirst$6(ItemStack.java:189) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.item.ItemStack$$Lambda$11662/173623542.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:189) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:280) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1433) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:927) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.66.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1487365582.call(Unknown Source) [forge-1.16.1-32.0.66.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.yogpc.qp.machines.item.ItemListEditor.onItemUseFirst(ItemListEditor.scala:64)
	at net.minecraft.item.ItemStack.lambda$onItemUseFirst$6(ItemStack.java:189)
	at net.minecraft.item.ItemStack$$Lambda$11662/173623542.apply(Unknown Source)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200)
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:189)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:280)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1339)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596)

Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:602)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1487365582.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.66
	FML Language Providers: 
		javafml@32.0
		minecraft@1
		kotori_scala@2.13.2-build-2


```

**Comment by Kotori316** [comment]
Fixed.

The List Editor should be enchanted with an enchantment the machine has.
